<?php

function zhazha_block_info()
{
  $blocks['user_detail_info'] = array(
    'info' =>'user detail information',
    'status' => FALSE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'user/*',
    'cache' => DRUPAL_CACHE_PER_USER,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function zhazha_block_view($delta = '')
{
  switch ($delta) {
    case 'user_detail_info': {
      $block['subject'] = 'sdafsad';
      $block['content'] = 'adfsadfdasfdsaf';
      return $block;
    }
    default: {
      break;
    }
  }
}

/**
 * Implements hook_menu_alter().
 */
function zhazha_menu_alter(&$items)
{
  dpm($items);

  $items['user/%user/shortcuts']['access callback'] = FALSE;

  $items['user/%user/track/navigation']['access callback'] = FALSE;

  $items['node/%node/track']['access callback'] = FALSE;

  $items['user/%user']['access callback'] = FALSE;

  $items['user/%user/edit']['access callback'] = FALSE;

  $items['user']['page callback'] = 'zhazha_user_page';
}

function zhazha_user_page(){

  global $user;
  if ($user->uid) {
    menu_set_active_item('user/' . $user->uid.'/works');
    return menu_execute_active_handler(NULL, FALSE);
  }
  else {
    return drupal_get_form('user_login');
  }
}